site_name: Omslite
site_url: http://omslite.site/
nav:
  - "Мотивация и цели":
    - index.md
  - "Инструкции":
    - user/omsite.md
    - user/demodb.md
    - user/sprav.md
    - "Справочники":
      - user/sprav/local.md
      - user/sprav/prof.md
      - user/sprav/pmu.md
    - user/clinic.md
    - user/reestr.md
  - "Технические детали":
    - admin/struct.md
    - admin/workdb.md
    - admin/jwt_auth.md
    - admin/pg_rest.md
    - admin/task_rest.md
    - admin/spa.md
    - admin/local_deploy.md
  - "Регистрация МО":
    - service/mo_register.md
theme: readthedocs