site_name: Omslite
site_url: http://omslite.site/
nav:
  - "Мотивация и цели":
    - index.md
  - "Инструкции":
    - user/omsite.md
    - user/demodb.md
    - "Приложение Справочники":
      - user/sprav/sprav.md
      - user/sprav/local.md
      - user/sprav/prof.md
      - user/sprav/pmu.md
      - user/sprav/comm.md
      - user/sprav/tarif.md
    - "Приложение Клиника":
      - user/clinic/clinic.md
      - user/clinic/cards_find.md
      - user/clinic/cards_edit.md
      - user/clinic/talons_find.md
      - user/clinic/talons_edit.md
      - user/clinic/tmpls_find.md
      - user/clinic/tmpls_edit.md
    - "Приложение Реестры":
      - user/reestr/reestr.md
      - user/reestr/packs.md
      - user/reestr/errors.md
      - user/reestr/invoice.md
  - "Технические детали":
    - admin/struct.md
    - admin/workdb.md
    - admin/pg_rest.md
    - admin/task_rest.md
    - admin/local_deploy.md
    - admin/jwt_auth.md
    - admin/access.md
    - admin/spa.md
    - admin/barsxml.md
    - admin/task_rest_api.md
    - admin/tk_errors.md
    - admin/invoice.md
  - "Регистрация МО":
    - service/mo_register.md
    - service/user_profile.md
    - service/mo_profile.md
theme: readthedocs